### ISSUE TITLE
 [WCER-E1] Background script entry is required';

### ISSUE THREAD

**Issue by lv99** [webclipper/web-clipper#410]
**Bug 描述**

用yarn启动失败，请问怎么解决

**复现步骤**

重现的步骤：

1. 根据Develop的步骤，执行到 yarn dev // Chrome
2. 看到错误

yarn run v1.22.4
$ cross-env NODE_ENV=development webpack --config webpack/webpack.dev.js --watch // Chrome
[ Starting the Chrome Hot Plugin Reload Server... ]

webpack is watching the files…

TypeError: [WCER-E1] function(obj) {
obj || (obj = {});
var __t, __p = '';
with (obj) {
__p += 'Background script entry is required';

}
return __p
}.
Visit https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader/wiki/General-Information#WCER-E1 for complete details

    at C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\webpack-chrome-extension-reloader\dist\webpack:\src\ChromeExtensionReloader.ts:57:15
    at C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\webpack-chrome-extension-reloader\dist\webpack:\src\webpack\CompilerEventsFacade.ts:23:25
    at SyncHook.eval (eval at create (C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:5:1)
    at SyncHook.lazyCompileHook (C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\webpack\lib\Compilation.js:1413:42
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\webpack\lib\Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\webpack\lib\Compilation.js:1405:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\webpack\lib\Compilation.js:1342:27)
    at C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\webpack\lib\Compiler.js:675:18
    at C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\webpack\lib\Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\webpack\lib\Compilation.js:1253:28)
    at C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\webpack\lib\Compiler.js:672:17
    at eval (eval at create (C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\webpack\lib\Compilation.js:1185:12
    at C:\Users\lv99\Documents\GitHub\web-clipper\node_modules\webpack\lib\Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**请填写以下信息**

- 笔记平台: confluence
- 浏览器 chrome
- 版本 1.22.4

**其他背景**
windows和macos都是同样的报错

**Comment by DiamondYuan** [comment]
这个错误好像可以忽略的。

**Comment by DiamondYuan** [comment]
我替换了依赖 webpack-chrome-extension-reloader -> webpack-extension-reloader

你可以拉最新的代码试试看。

推荐用 yarn 来安装依赖。
